language: node_js
node_js:
  - ">=.10"
before_install: npm install -g grunt-cli
install: npm install
before_script:
  - npm install -g bower
  - bower install
script: grunt build
after_success: grunt deploy